### ISSUE TITLE
Unable to withdraw in mobile browser

### ISSUE THREAD

**Issue by druiz0992** [hermeznetwork/wallet-ui#614]
## Summary of Bug

I am trying to withdraw some funds using an iPhone with Wallet Connect. After I complete the withdraw, the wallet reports an error.

### Browser information

- Browser: `Safari`
- Device/OS: `IOS`

### Additional Information & Screenshots:

https://media.discordapp.net/attachments/869601011768107128/869609989168320542/Screenshot_2021-07-27_at_17.59.30.png?width=301&height=525

**Comment by adrifdez** [comment]
I've withdraw hez and eth tokens without problems on an iPhone on local and testnet.
I've had problems withdrawing from wallet.hermez because says "Enter a valid value" 

![167E4912-73E8-4FE1-A9A4-813269F3FBB5.jpg](https://images.zenhubusercontent.com/60efdd095da309715fee160a/2a9ebb7b-18b6-4b49-bfc0-7ed200a59023)

**Comment by AlbertoElias** [comment]
It seems like this can be closed. We need to deploy to mainnet asap
