### ISSUE TITLE
Deposit on Brave browser doesn't work with Shields activated

### ISSUE THREAD

**Issue by AlbertoElias** [hermeznetwork/wallet-ui#791]
Some users have attempted to Deposit DAI with Metamask on Brave (mainnet) and it has failed. If they used Chrome or deactivated shields, it works

**Comment by elias-garcia** [comment]
I've been personally using Brave with the shields activated for a long time and never had a problem with the wallet... The user who has reported this issue has the Brave shields deactivated but he has two Brave add-ons which are also meant to block ads/popups:

- Microsoft Defender Browser Protection
- MalwareBytes Browser Guard

So the problem is likely to happen with any of this add-ons.
